# Generated by Django 5.2.11 on 2026-02-27 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='employee_images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('Finance', 'Finance'), ('Marketing', 'Marketing')], max_length=50)),
            ],
        ),
    ]
